version: '3'
services:
  database:
    image: mysql:5.7
    container_name: crudmysql_database_container
    ports:
      - 3306:3306
    volumes:
      - ./database:/data/application
    command: --init-file /data/application/init.sql
    networks:
      - crud_net
    environment:
      - MYSQL_ROOT_USER=gfmois
      - MYSQL_ROOT_PASSWORD=contraseña
      - MYSQL_PASSWORD=1234
  web:
    build: ./application
    container_name: crudmysql_web_container
    ports:
      - 3000:3000
    networks:
      - crud_net
    command: sh -c "/usr/src/app/wait-for-it.sh -t 0 database:3306 -- npm run dev"
    depends_on:
      - database
    
networks:
  crud_net: